
INSERT INTO SKROL(NOMBREROL, ESTADO, FECHACREACION)
VALUES('ADMIN', true, current_timestamp);

INSERT INTO SKUSUARIO
(NOMBREUSUARIO, PASSWORD, ESTADO, FECHACREACION)
VALUES('admin', '$2a$10$XURPShQNCsLjp1ESc2laoObo9QZDhxz73hJPaEv7/cBha4pk0AgP.', true, current_timestamp);

INSERT INTO SKUSUARIOROL
(ROLPK, USUARIOPK, ESTADO, FECHACREACION)
VALUES(1, 1, true, current_timestamp);

INSERT INTO SKTIPOPAGO
(descripcionpago, estado, fechacreacion)
VALUES ('TARJETA DE CREDITO', true, CURRENT_TIMESTAMP);

INSERT INTO SKTIPOPAGO
(descripcionpago, estado, fechacreacion)
VALUES ('TRANSFERENCIA BANCARIA', true, CURRENT_TIMESTAMP);

INSERT INTO  SKCLASIFICACION
(NOMBRE, ESTADO, FECHACREACION)
VALUES ('DC Comics', true, current_timestamp);

INSERT INTO  SKCLASIFICACION
(NOMBRE, ESTADO, FECHACREACION)
VALUES ('Marvel', true, current_timestamp);

INSERT INTO SKARTICULO
(CLASIFICACIONPK, CODIGOBARRAS, DESCRIPCION, PRECIO, EXISTENCIA, ESTADO, FECHACREACION)
VALUES (1,'8257480498472', 'Camiseta Batman inicia M', 23, 100, '1', current_timestamp);

INSERT INTO SKARTICULO
(CLASIFICACIONPK, CODIGOBARRAS, DESCRIPCION, PRECIO, EXISTENCIA, ESTADO, FECHACREACION)
VALUES (1,'8257480498471', 'Camiseta Batman inicia S', 16, 100, '1', current_timestamp);

INSERT INTO SKARTICULO
(CLASIFICACIONPK, CODIGOBARRAS, DESCRIPCION, PRECIO, EXISTENCIA, ESTADO, FECHACREACION)
VALUES (1,'8257480498473', 'Camiseta Batman inicia XS', 18, 100, '1', current_timestamp);

INSERT INTO SKARTICULO
(CLASIFICACIONPK, CODIGOBARRAS, DESCRIPCION, PRECIO, EXISTENCIA, ESTADO, FECHACREACION)
VALUES (1,'8257480498474', 'Camiseta Batman inicia', 23, 100, '1', current_timestamp);

INSERT INTO SKARTICULO
(CLASIFICACIONPK, CODIGOBARRAS, DESCRIPCION, PRECIO, EXISTENCIA, ESTADO, FECHACREACION)
VALUES (1,'8257480498475', 'Camiseta Batman inicia', 23, 100, '1', current_timestamp);

INSERT INTO SKARTICULO
(CLASIFICACIONPK, CODIGOBARRAS, DESCRIPCION, PRECIO, EXISTENCIA, ESTADO, FECHACREACION)
VALUES (1,'8257480498476', 'Camiseta Batman inicia', 23, 100, '1', current_timestamp);

INSERT INTO SKARTICULO
(CLASIFICACIONPK, CODIGOBARRAS, DESCRIPCION, PRECIO, EXISTENCIA, ESTADO, FECHACREACION)
VALUES (1,'8257480498477', 'Camiseta Batman inicia', 23, 100, '1', current_timestamp);

INSERT INTO SKARTICULO
(CLASIFICACIONPK, CODIGOBARRAS, DESCRIPCION, PRECIO, EXISTENCIA, ESTADO, FECHACREACION)
VALUES (1,'8257480498478', 'Camiseta Batman inicia', 23, 100, '1', current_timestamp);

INSERT INTO SKARTICULO
(CLASIFICACIONPK, CODIGOBARRAS, DESCRIPCION, PRECIO, EXISTENCIA, ESTADO, FECHACREACION)
VALUES (1,'8257480498479', 'Camiseta Batman inicia', 23, 100, '1', current_timestamp);

INSERT INTO SKARTICULO
(CLASIFICACIONPK, CODIGOBARRAS, DESCRIPCION, PRECIO, EXISTENCIA, ESTADO, FECHACREACION)
VALUES (1,'8257480498410', 'Camiseta Batman inicia', 23, 100, '1', current_timestamp);

INSERT INTO SKARTICULO
(CLASIFICACIONPK, CODIGOBARRAS, DESCRIPCION, PRECIO, EXISTENCIA, ESTADO, FECHACREACION)
VALUES (1,'8257480498411', 'Camiseta Batman inicia', 23, 100, '1', current_timestamp);

INSERT INTO SKARTICULO
(CLASIFICACIONPK, CODIGOBARRAS, DESCRIPCION, PRECIO, EXISTENCIA, ESTADO, FECHACREACION)
VALUES (1,'8257480498412', 'Camiseta Batman inicia', 23, 100, '1', current_timestamp);

INSERT INTO SKARTICULO
(CLASIFICACIONPK, CODIGOBARRAS, DESCRIPCION, PRECIO, EXISTENCIA, ESTADO, FECHACREACION)
VALUES (1,'8257480498413', 'Comic Batman inicia ', 2, 100, '1', current_timestamp);

INSERT INTO SKARTICULO
(CLASIFICACIONPK, CODIGOBARRAS, DESCRIPCION, PRECIO, EXISTENCIA, ESTADO, FECHACREACION)
VALUES (1,'8257480498414', 'Camiseta Batman inicia', 23, 100, '1', current_timestamp);

INSERT INTO SKARTICULO
(CLASIFICACIONPK, CODIGOBARRAS, DESCRIPCION, PRECIO, EXISTENCIA, ESTADO, FECHACREACION)
VALUES (1,'8257480498422', 'Camiseta Batman inicia', 23, 100, '1', current_timestamp);

INSERT INTO SKARTICULO
(CLASIFICACIONPK, CODIGOBARRAS, DESCRIPCION, PRECIO, EXISTENCIA, ESTADO, FECHACREACION)
VALUES (1,'8257485498472', 'Camiseta Batman inicia', 23, 100, '1', current_timestamp);

INSERT INTO SKARTICULO
(CLASIFICACIONPK, CODIGOBARRAS, DESCRIPCION, PRECIO, EXISTENCIA, ESTADO, FECHACREACION)
VALUES (1,'8257460498472', 'Camiseta Batman inicia', 23, 100, '1', current_timestamp);

INSERT INTO SKARTICULO
(CLASIFICACIONPK, CODIGOBARRAS, DESCRIPCION, PRECIO, EXISTENCIA, ESTADO, FECHACREACION)
VALUES (1,'8257485698472', 'Camiseta Batman inicia', 23, 100, '1', current_timestamp);

INSERT INTO SKARTICULO
(CLASIFICACIONPK, CODIGOBARRAS, DESCRIPCION, PRECIO, EXISTENCIA, ESTADO, FECHACREACION)
VALUES (1,'8257480268472', 'Camiseta Batman inicia', 23, 100, '1', current_timestamp);

INSERT INTO SKARTICULO
(CLASIFICACIONPK, CODIGOBARRAS, DESCRIPCION, PRECIO, EXISTENCIA, ESTADO, FECHACREACION)
VALUES (1,'8257680498472', 'Camiseta Batman inicia', 23, 100, '1', current_timestamp);

INSERT INTO SKARTICULO
(CLASIFICACIONPK, CODIGOBARRAS, DESCRIPCION, PRECIO, EXISTENCIA, ESTADO, FECHACREACION)
VALUES (1,'8257422498472', 'Camiseta Batman inicia', 23, 100, '1', current_timestamp);

INSERT INTO SKARTICULO
(CLASIFICACIONPK, CODIGOBARRAS, DESCRIPCION, PRECIO, EXISTENCIA, ESTADO, FECHACREACION)
VALUES (1,'8257476498472', 'Camiseta Batman inicia', 23, 100, '1', current_timestamp);

INSERT INTO SKARTICULO
(CLASIFICACIONPK, CODIGOBARRAS, DESCRIPCION, PRECIO, EXISTENCIA, ESTADO, FECHACREACION)
VALUES (1,'8257484498472', 'Camiseta Batman inicia', 23, 100, '1', current_timestamp);

INSERT INTO SKARTICULO
(CLASIFICACIONPK, CODIGOBARRAS, DESCRIPCION, PRECIO, EXISTENCIA, ESTADO, FECHACREACION)
VALUES (1,'8257480128472', 'Camiseta Batman inicia', 23, 100, '1', current_timestamp);

INSERT INTO SKARTICULO
(CLASIFICACIONPK, CODIGOBARRAS, DESCRIPCION, PRECIO, EXISTENCIA, ESTADO, FECHACREACION)
VALUES (1,'82574456498472', 'Camiseta Batman inicia', 23, 100, '1', current_timestamp);

INSERT INTO SKARTICULO
(CLASIFICACIONPK, CODIGOBARRAS, DESCRIPCION, PRECIO, EXISTENCIA, ESTADO, FECHACREACION)
VALUES (1,'825748678498472', 'Camiseta Batman inicia', 23, 100, '1', current_timestamp);

INSERT INTO SKARTICULO
(CLASIFICACIONPK, CODIGOBARRAS, DESCRIPCION, PRECIO, EXISTENCIA, ESTADO, FECHACREACION)
VALUES (1,'8257460498472', 'Camiseta Batman inicia', 23, 100, '1', current_timestamp);

INSERT INTO SKARTICULO
(CLASIFICACIONPK, CODIGOBARRAS, DESCRIPCION, PRECIO, EXISTENCIA, ESTADO, FECHACREACION)
VALUES (1,'8257094498472', 'Camiseta Batman inicia', 23, 100, '1', current_timestamp);

INSERT INTO SKARTICULO
(CLASIFICACIONPK, CODIGOBARRAS, DESCRIPCION, PRECIO, EXISTENCIA, ESTADO, FECHACREACION)
VALUES (1,'82574842298472', 'Camiseta Batman inicia', 23, 100, '1', current_timestamp);

INSERT INTO SKARTICULO
(CLASIFICACIONPK, CODIGOBARRAS, DESCRIPCION, PRECIO, EXISTENCIA, ESTADO, FECHACREACION)
VALUES (1,'82574804942272', 'Camiseta Batman inicia', 23, 100, '1', current_timestamp);

INSERT INTO SKARTICULO
(CLASIFICACIONPK, CODIGOBARRAS, DESCRIPCION, PRECIO, EXISTENCIA, ESTADO, FECHACREACION)
VALUES (1,'8257480498472', 'Camiseta Batman inicia', 23, 100, '1', current_timestamp);

INSERT INTO SKARTICULO
(CLASIFICACIONPK, CODIGOBARRAS, DESCRIPCION, PRECIO, EXISTENCIA, ESTADO, FECHACREACION)
VALUES (1,'82574804528472', 'Camiseta Batman inicia', 23, 100, '1', current_timestamp);

INSERT INTO SKARTICULO
(CLASIFICACIONPK, CODIGOBARRAS, DESCRIPCION, PRECIO, EXISTENCIA, ESTADO, FECHACREACION)
VALUES (1,'8257320498472', 'Camiseta Batman inicia', 23, 100, '1', current_timestamp);

INSERT INTO SKARTICULO
(CLASIFICACIONPK, CODIGOBARRAS, DESCRIPCION, PRECIO, EXISTENCIA, ESTADO, FECHACREACION)
VALUES (1,'8257480495672', 'Camiseta Batman inicia', 23, 100, '1', current_timestamp);

INSERT INTO SKARTICULO
(CLASIFICACIONPK, CODIGOBARRAS, DESCRIPCION, PRECIO, EXISTENCIA, ESTADO, FECHACREACION)
VALUES (1,'8257480498342', 'Camiseta Batman inicia', 23, 100, '1', current_timestamp);

INSERT INTO SKARTICULO
(CLASIFICACIONPK, CODIGOBARRAS, DESCRIPCION, PRECIO, EXISTENCIA, ESTADO, FECHACREACION)
VALUES (1,'8257480497872', 'Camiseta Batman inicia', 23, 100, '1', current_timestamp);

INSERT INTO SKARTICULO
(CLASIFICACIONPK, CODIGOBARRAS, DESCRIPCION, PRECIO, EXISTENCIA, ESTADO, FECHACREACION)
VALUES (1,'8257480423472', 'Camiseta Batman inicia', 23, 100, '1', current_timestamp);

INSERT INTO SKARTICULO
(CLASIFICACIONPK, CODIGOBARRAS, DESCRIPCION, PRECIO, EXISTENCIA, ESTADO, FECHACREACION)
VALUES (1,'8257467498472', 'Camiseta Batman inicia', 23, 100, '1', current_timestamp);

INSERT INTO SKARTICULO
(CLASIFICACIONPK, CODIGOBARRAS, DESCRIPCION, PRECIO, EXISTENCIA, ESTADO, FECHACREACION)
VALUES (1,'8257480496572', 'Camiseta Batman inicia', 23, 100, '1', current_timestamp);

INSERT INTO SKARTICULO
(CLASIFICACIONPK, CODIGOBARRAS, DESCRIPCION, PRECIO, EXISTENCIA, ESTADO, FECHACREACION)
VALUES (1,'8257480465472', 'Camiseta Batman inicia', 23, 100, '1', current_timestamp);

INSERT INTO SKARTICULO
(CLASIFICACIONPK, CODIGOBARRAS, DESCRIPCION, PRECIO, EXISTENCIA, ESTADO, FECHACREACION)
VALUES (1,'8257480467472', 'Camiseta Batman inicia', 23, 100, '1', current_timestamp);

INSERT INTO SKARTICULO
(CLASIFICACIONPK, CODIGOBARRAS, DESCRIPCION, PRECIO, EXISTENCIA, ESTADO, FECHACREACION)
VALUES (1,'8257480231872', 'Camiseta Batman inicia', 23, 100, '1', current_timestamp);

INSERT INTO SKARTICULO
(CLASIFICACIONPK, CODIGOBARRAS, DESCRIPCION, PRECIO, EXISTENCIA, ESTADO, FECHACREACION)
VALUES (1,'82574804954372', 'Camiseta Batman inicia', 23, 100, '1', current_timestamp);

INSERT INTO SKARTICULO
(CLASIFICACIONPK, CODIGOBARRAS, DESCRIPCION, PRECIO, EXISTENCIA, ESTADO, FECHACREACION)
VALUES (1,'8257480498452', 'Camiseta Batman inicia', 23, 100, '1', current_timestamp);

INSERT INTO SKARTICULO
(CLASIFICACIONPK, CODIGOBARRAS, DESCRIPCION, PRECIO, EXISTENCIA, ESTADO, FECHACREACION)
VALUES (1,'8257230498472', 'Camiseta Batman inicia', 23, 100, '1', current_timestamp);

INSERT INTO SKARTICULO
(CLASIFICACIONPK, CODIGOBARRAS, DESCRIPCION, PRECIO, EXISTENCIA, ESTADO, FECHACREACION)
VALUES (1,'8257480498562', 'Camiseta Batman inicia', 23, 100, '1', current_timestamp);

INSERT INTO SKARTICULO
(CLASIFICACIONPK, CODIGOBARRAS, DESCRIPCION, PRECIO, EXISTENCIA, ESTADO, FECHACREACION)
VALUES (1,'8257480238472', 'Camiseta Batman inicia', 23, 100, '1', current_timestamp);

INSERT INTO SKARTICULO
(CLASIFICACIONPK, CODIGOBARRAS, DESCRIPCION, PRECIO, EXISTENCIA, ESTADO, FECHACREACION)
VALUES (1,'8257480658472', 'Camiseta Batman inicia', 23, 100, '1', current_timestamp);

INSERT INTO SKARTICULO
(CLASIFICACIONPK, CODIGOBARRAS, DESCRIPCION, PRECIO, EXISTENCIA, ESTADO, FECHACREACION)
VALUES (1,'8257480498622', 'Camiseta Batman inicia', 23, 100, '1', current_timestamp);

INSERT INTO SKARTICULO
(CLASIFICACIONPK, CODIGOBARRAS, DESCRIPCION, PRECIO, EXISTENCIA, ESTADO, FECHACREACION)
VALUES (1,'8257480494572', 'Camiseta Batman inicia', 23, 100, '1', current_timestamp);

INSERT INTO SKARTICULO
(CLASIFICACIONPK, CODIGOBARRAS, DESCRIPCION, PRECIO, EXISTENCIA, ESTADO, FECHACREACION)
VALUES (1,'8257480497677', 'Camiseta Batman inicia', 23, 100, '1', current_timestamp);