
INSERT INTO SKROL(NOMBREROL, ESTADO, FECHACREACION)
VALUES('ADMIN', true, current_timestamp);

INSERT INTO SKUSUARIO
(NOMBREUSUARIO, PASSWORD, ESTADO, FECHACREACION)
VALUES('admin', '$2a$10$XURPShQNCsLjp1ESc2laoObo9QZDhxz73hJPaEv7/cBha4pk0AgP.', true, current_timestamp);

INSERT INTO SKUSUARIOROL
(ROLPK, USUARIOPK, ESTADO, FECHACREACION)
VALUES(1, 1, true, current_timestamp);